name: Auto Commit and Push

on:
  push:
    branches:
      - main  # Change this if your branch name is different
  schedule:
    - cron: "0 * * * *"  # Runs every hour

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "github-actions@github.com"

      - name: Pull latest changes
        run: git pull origin main

      - name: Auto-commit changes
        run: |
          git add .
          git commit -m "Automated commit from GitHub Actions" || echo "No changes to commit"
          git push origin main
